name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0" # Set to your PHP version

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-scripts --no-dev --optimize-autoloader

      - name: Setup SSH Keys and Known Hosts
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          rsync -avz --exclude '/vendor' --exclude '/node_modules' ./ ubuntu@your-ec2-ip:~/path/to/your/app
          ssh ubuntu@your-ec2-ip "cd ~/path/to/your/app && php artisan migrate --force"
